<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercices Formulaires</title>
        <link rel="stylesheet" href="assets/styles/style.css">
    </head>
    <body>
        <?php require "templates/partials/_header.phtml"; ?>

        <?php
        if ($template === 'about') {
            require "templates/partials/_about.phtml";
        } elseif ($template === 'contact') {
            require "templates/partials/_contact.phtml";
        } else {
            require "templates/partials/_homepage.phtml";
        }
        ?>

        <?php require "templates/partials/_footer.phtml"; ?>
    </body>
</html>