<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <form method="post" action="templates/controllers/user-form.php">
    <fieldset>
        <label for="email">Adresse email :</label>
        <input type="email" id="email" name="email" required>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>
    </fieldset>
    <fieldset>
        <label for="confirm_password">Confirmer le mot de passe :</label>
        <input type="password" id="confirm_password" name="confirm_password" required>
    </fieldset>
    <fieldset>
        <label for="newsletter">S'inscrire à la newsletter :</label>
        <input type="checkbox" id="newsletter" name="newsletter">
    </fieldset>
    <button type="submit">S'inscrire</button>
</form>

</main>