<main class="container py-5">
    <form>
        <fieldset class="my-1">
            <label for="username" class="form-label">
                <?= $this->translator->translate("register_username_text") ?>
            </label>
            <input type="text" name="username" id="username" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                <?= $this->translator->translate("register_email_text") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                <?= $this->translator->translate("register_password_text") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
                <?= $this->translator->translate("register_confirm_password_text") ?>
            </label>
            <input type="password" name="confirm-password" id="confirm-password" class="form-control" />
        </fieldset>
        <fieldset class="my-4">
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("register_submit_button") ?></button>
        </fieldset>
    </form>
    <p>
        <?= $this->translator->translate("register_already_account") ?> <a href="index.php"> <?= $this->translator->translate("nav_login_link") ?> </a>
    </p>
</main>