<form class="col mt-5" action="../logic/create-user.php" method="POST">
    <fieldset>
        <label for="username" class="form-label">Nom d'utilisateur</label>
        <input type="text" id="username" name="username" class="form-control" />
    </fieldset>
    <fieldset>
        <label for="email" class="form-label">Email</label>
        <input type="email" id="email" name="email" class="form-control" />
    </fieldset>
    <fieldset>
        <label for="password" class="form-label">Mot de passe</label>
        <input type="password" id="password" name="password" class="form-control" />
    </fieldset>
    <fieldset>
        <label for="role" class="form-label">Rôle</label>
        <select class="form-control" id="role" name="role">
            <option value="user">User</option>
            <option value="admin">Admin</option>
        </select>
    </fieldset>
    <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
</form>