<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>Distorsion</title>

    <!-- Lien vers la feuille de style principale -->
    <link rel="stylesheet" href="../assets/css/style.css">

</head>

<body>
    <div class="layout">
        <aside class="sidebar">

            <main class="container">
                <!-- Début du contenu principal -->
                <h2 class="navbar-brand"><a href="index.php?route=/">Distorsion</a></h2>
                <ul>
                    <li><a href="index.php?route=/categories">Catégories</a></li>
                    <li><a href="index.php?route=/rooms">Salons</a></li>
                    <li><a href="index.php?route=/about">À propos</a></li>
                    <?php
                    if (session_status() === PHP_SESSION_NONE) {
                        session_start();
                    }

                    if (!empty($_SESSION['user_id'])) :
                    ?>
                        <li><a href="index.php?route=/logout">Se déconnecter</a></li>
                    <?php else: ?>
                        <li><a href="index.php?route=/login-form">Se connecter</a></li>
                        <li><a href="index.php?route=/register-form">S'inscrire</a></li>
                    <?php endif; ?>
                </ul>

        </aside>

        <main class="content">