<?php require "logic/display-users.php" ?>

<table class="col my-5 table table-striped">
    <thead>
    <tr>
        <th>
            #
        </th>
        <th>
            Nom d'utilisateur
        </th>
        <th>
            Email
        </th>
        <th>
            Mot de passe
        </th>
        <th>
            Rôle
        </th>
        <th>
            Supprimer
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($users as $user) { ?>
        <tr>
            <td> <?= $user->getId(); ?> </td>
            <td> <?= $user->getUsername(); ?> </td>
            <td> <?= $user->getEmail(); ?> </td>
            <td> <?= $user->getPassword(); ?> </td>
            <td> <?= $user->getRole(); ?> </td>
            <td>
                <a href="../logic/delete-user.php?id=<?= $user->getId() ?>" class="btn btn-danger"><scan class="bi-trash-fill"></scan></a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <tfoot>
    <tr>
        <th>
            #
        </th>
        <th>
            Nom d'utilisateur
        </th>
        <th>
            Email
        </th>
        <th>
            Mot de passe
        </th>
        <th>
            Rôle
        </th>
        <th>
            Supprimer
        </th>
    </tr>
    </tfoot>
</table>
