<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentification MVC</title>
    <link rel="stylesheet" href="assets/styles/style.css">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li><a href="index.php?route=connexion">Connexion</a></li>
                <li><a href="index.php?route=inscription">Inscription</a></li>
                <li><a href="index.php?route=espace-perso">Espace Perso</a></li>
            </ul>
        </nav>
    </header>
    <hr>
    <?php
    if ($route === 'connexion') {
        require 'templates/connexion.phtml';
    } elseif ($route === 'inscription') {
        require 'templates/inscription.phtml';
    } elseif ($route === 'espace-perso') {
        require 'templates/espace-perso.phtml';
    } else {
        require 'templates/notFound.phtml';
    }
    ?>
    <footer>
        <p>&copy; 2025 - Authentification MVC</p>
    </footer>
</body>

</html>