<?php $route = 'users/create.phtml'; ?>
<h2>Créer un utilisateur</h2>
<form method="POST" action="index.php?route=check_create_user">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" required>

    <label for="first_name">Prénom</label>
    <input type="text" name="first_name" id="first_name" required>

    <label for="last_name">Nom</label>
    <input type="text" name="last_name" id="last_name" required>

    <button type="submit">Créer</button>
</form>