<body>
    <h1>Créer un utilisateur</h1>
    <form action="index.php?route=check_create_user" method="post">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br><br>

        <label for="first_name">Prénom:</label>
        <input type="text" id="first_name" name="first_name" required><br><br>

        <label for="last_name">Nom:</label>
        <input type="text" id="last_name" name="last_name" required><br><br>

        <input type="submit" value="Créer">
    </form>
</body>