<h1>Liste des utilisateurs</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?= $user->getId() ?></td>
                <td><?= $user->getEmail() ?></td>
                <td><?= $user->getFirstName() ?></td>
                <td><?= $user->getLastName() ?></td>
                <td>
                    <a href="index.php?route=show_user&id=<?= $user->getId() ?>">Voir</a>
                    <a href="index.php?route=update_user&id=<?= $user->getId() ?>">Modifier</a>
                    <a href="index.php?route=delete_user&id=<?= $user->getId() ?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>