<h1>Mettre à jour un utilisateur</h1>
<form action="index.php?route=check_update_user" method="post">
    <input type="hidden" name="id" value="<?= $user->getId() ?>">
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" value="<?= $user->getEmail() ?>" required><br><br>

    <label for="first_name">Prénom:</label>
    <input type="text" id="first_name" name="first_name" value="<?= $user->getFirstName() ?>" required><br><br>

    <label for="last_name">Nom:</label>
    <input type="text" id="last_name" name="last_name" value="<?= $user->getLastName() ?>" required><br><br>

    <input type="submit" value="Mettre à jour">
</form>