<?php $route = 'users/update.phtml'; ?>
<h2>Mettre à jour l'utilisateur</h2>
<form method="POST" action="index.php?route=check_update_user">
    <input type="hidden" name="id" value="<?= $user->getId() ?>">

    <label for="email">Email</label>
    <input type="email" name="email" id="email" value="<?= $user->getEmail() ?>" required>

    <label for="first_name">Prénom</label>
    <input type="text" name="first_name" id="first_name" value="<?= $user->getFirstName() ?>" required>

    <label for="last_name">Nom</label>
    <input type="text" name="last_name" id="last_name" value="<?= $user->getLastName() ?>" required>

    <button type="submit">Mettre à jour</button>
</form>