<main class="p-5">
    <h1>
        <?php echo $category["name"]; ?>
    </h1>
    <section class="my-4">
        <h2>
            Liste des articles
        </h2>
        
        <ul class="row g-3 p-0" style="list-style:none;">
            <?php foreach($categoryPosts as $post) : ?>
                <li class="col-3">
                    <article class="card pb-4">
                        <img 
                        src="<?php echo $post['url']; ?>" 
                        class="card-img-top" 
                        alt="<?php echo $post['alt']; ?>">
                        <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                            <?php echo $post["title"]; ?>
                        </h3>
                        <a href="index.php?route=post&post=<?php echo $post["id"]; ?>" class="btn btn-primary mx-2">Lire l'article</a>
                    </article>
                </li>
            <?php endforeach; ?>
        </ul>
        
    </section>
</main>