<main class="p-5">
    <h1>
        Page d'accueil
    </h1>
    <section class="my-4">
        <h2>
            Backend
        </h2>
        <ul class="row g-3 p-0" style="list-style:none;">
            <li class="col-3">
                <article class="card pb-4">
                    <img src="https://kornog-dev.github.io/BRE03/php/j7/soutien/backend-1.png" class="card-img-top" alt="Un éléphant cartoon tenant un 8">
                    <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                        Les nouveautés de PHP 8
                    </h3>
                    <a href="#" class="btn btn-primary mx-2">Lire l'article</a>
                </article>
            </li>
            <li class="col-3">
                <article class="card pb-4">
                    <img src="https://kornog-dev.github.io/BRE03/php/j7/soutien/backend-2.png" class="card-img-top" alt="Un schéma de fonctionnement entre un ordinateur et une base de données">
                    <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                        Comment le MVC a conquis le développement PHP ?
                    </h3>
                    <a href="#" class="btn btn-primary mx-2">Lire l'article</a>
                </article>
            </li>
        </ul>
    </section>
    <section class="my-4">
        <h2>
            Frontend
        </h2>
        <ul class="row g-3 p-0" style="list-style:none;">
            <li class="col-3">
                <article class="card pb-4">
                    <img src="https://kornog-dev.github.io/BRE03/php/j7/soutien/frontend-1.png" class="card-img-top" alt="Texte de l'image : Vanilla JavaScript vs various JavaScript Frameworks">
                    <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                        JavaScript Vanilla vs Framework : comment choisir ?
                    </h3>
                    <a href="#" class="btn btn-primary mx-2">Lire l'article</a>
                </article>
            </li>
            <li class="col-3">
                <article class="card pb-4">
                    <img src="https://kornog-dev.github.io/BRE03/php/j7/soutien/frontend-2.png" class="card-img-top" alt="Schéma de fonctionnement d'un réseau">
                    <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                        Pourquoi utiliser les Web Workers ?
                    </h3>
                    <a href="#" class="btn btn-primary mx-2">Lire l'article</a>
                </article>
            </li>
        </ul>
    </section>
    <section class="my-4">
        <h2>
            Intégration
        </h2>
        <ul class="row g-3 p-0" style="list-style:none;">
            <li class="col-3">
                <article class="card pb-4">
                    <img src="https://kornog-dev.github.io/BRE03/php/j7/soutien/integration-1.png" class="card-img-top" alt="Texte de l'image : HTML 5">
                    <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                        HTML5 : Une révolution
                    </h3>
                    <a href="#" class="btn btn-primary mx-2">Lire l'article</a>
                </article>
            </li>
            <li class="col-3">
                <article class="card pb-4">
                    <img src="https://kornog-dev.github.io/BRE03/php/j7/soutien/integration-2.png" class="card-img-top" alt="Texte de l'image : CSS vers Sass">
                    <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                        Passer son CSS en Sass : le pour et le contre
                    </h3>
                    <a href="#" class="btn btn-primary mx-2">Lire l'article</a>
                </article>
            </li>
        </ul>
    </section>
</main>